// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAPI.DBContext;

#nullable disable

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3");

            modelBuilder.Entity("ProjectAPI.Models.ClientDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ProjectAPI.Models.OrderListDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModify")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientDbId");

                    b.ToTable("OrderLists");
                });

            modelBuilder.Entity("ProjectAPI.Models.OrderStringDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Leather")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderListDbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderListId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Size35")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size36")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size37")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size38")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size39")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size40")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size41")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderListDbId");

                    b.ToTable("OrderStrings");
                });

            modelBuilder.Entity("ProjectAPI.Models.OrderListDb", b =>
                {
                    b.HasOne("ProjectAPI.Models.ClientDb", null)
                        .WithMany("OrderLists")
                        .HasForeignKey("ClientDbId");
                });

            modelBuilder.Entity("ProjectAPI.Models.OrderStringDb", b =>
                {
                    b.HasOne("ProjectAPI.Models.OrderListDb", null)
                        .WithMany("OrderStrings")
                        .HasForeignKey("OrderListDbId");
                });

            modelBuilder.Entity("ProjectAPI.Models.ClientDb", b =>
                {
                    b.Navigation("OrderLists");
                });

            modelBuilder.Entity("ProjectAPI.Models.OrderListDb", b =>
                {
                    b.Navigation("OrderStrings");
                });
#pragma warning restore 612, 618
        }
    }
}
